apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: test-python-az
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.cluster-vwvs6.vwvs6.sandbox862.opentlc.com/rhtap/rhtap-test:azure-c1abe8cbc2780e74cb3fb6f309f5815b2b057733
        name: container-image  
